### ISSUE TITLE
Compiling error in CircuitBlocks

### ISSUE THREAD

**Issue by bugtesterdani** [CircuitMess/Snake#1]
I get the error:

Running
Compile error. Check your code then try again.

When trying to build this Code inside CircuitBlocks.
Is it a CircuitBlocks error or is something wrong with the code?

After i try to figure out the error position, i found that the addOscillator(osc); Function is not compiling.

Could someone maybe tell me a fixaround?
Thanks

**Comment by bugtesterdani** [comment]
Fixed when used the Arduino IDE.

**Comment by filipbudisa** [comment]
Make sure you turn off the minimal compile in CircuitBlocks. It turns off a lot of stuff that isn't critical and speeds up compilation time. Snake is one of those sketches that needs all of the functionalities of the Ringo lib to compile.
